# Generated by Django 6.0.3 on 2026-03-27 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('test1_percentage', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=300)),
                ('option_b', models.CharField(max_length=300)),
                ('option_c', models.CharField(max_length=300)),
                ('option_d', models.CharField(max_length=300)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('marks', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_questions', to='exams.examsession')),
            ],
        ),
        migrations.CreateModel(
            name='OneWordQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer', models.CharField(max_length=200)),
                ('corresponding_mcq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oneword', to='exams.mcqquestion')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oneword_questions', to='exams.examsession')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_email', models.EmailField(blank=True, max_length=254)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('test1_completed', models.BooleanField(default=False)),
                ('test2_completed', models.BooleanField(default=False)),
                ('test1_direct_marks', models.FloatField(default=0)),
                ('test2_bonus_marks', models.FloatField(default=0)),
                ('total_marks', models.FloatField(default=0)),
                ('max_possible_marks', models.FloatField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examsession')),
            ],
        ),
        migrations.CreateModel(
            name='Test1Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('promoted_to_test2', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test1_answers', to='exams.studentattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.mcqquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Test2Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.CharField(blank=True, max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test2_answers', to='exams.studentattempt')),
                ('oneword_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.onewordquestion')),
            ],
        ),
    ]
