# Generated by Django 6.0.3 on 2026-03-28 04:11

import django.db.models.deletion
import exams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_email', models.EmailField(blank=True, max_length=254)),
                ('code', models.CharField(default=exams.models.generate_code, max_length=20, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_codes', to='exams.examsession')),
            ],
        ),
        migrations.AddField(
            model_name='studentattempt',
            name='access_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt', to='exams.studentaccesscode'),
        ),
    ]
