# Generated by Django 6.0.3 on 2026-03-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_studentaccesscode_studentattempt_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='duration_minutes',
            field=models.IntegerField(default=30, help_text='Test duration in minutes'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Exam window closes at', null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='instructions',
            field=models.TextField(blank=True, default='1. Read all questions carefully.\n2. Each MCQ has only one correct answer.\n3. Do not refresh the page during the exam.\n4. The exam will auto-submit when time runs out.\n5. You cannot go back once you submit.'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Exam window opens at', null=True),
        ),
        migrations.AddField(
            model_name='studentattempt',
            name='test1_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
