# Generated by Django 6.0.3 on 2026-04-07 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examsession_duration_minutes_examsession_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='ai_questions_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examsession',
            name='use_ai_for_test2',
            field=models.BooleanField(default=False, help_text='Let AI generate Test 2 questions from MCQs'),
        ),
        migrations.AddField(
            model_name='studentaccesscode',
            name='enrollment_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentattempt',
            name='enrollment_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='test1answer',
            name='option_shuffle_map',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anthropic_api_key', models.CharField(blank=True, help_text='Your Anthropic API key for AI question generation', max_length=200)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
