# Generated by Django 6.0.3 on 2026-04-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examsession_ai_questions_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattempt',
            name='fullscreen_exit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentattempt',
            name='tab_switch_count',
            field=models.IntegerField(default=0),
        ),
    ]
