# Generated by Django 6.0.3 on 2026-04-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_studentattempt_fullscreen_exit_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='branch',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='examsession',
            name='faculty_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='examsession',
            name='semester',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='examsession',
            name='year',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
