from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('teacher/login/', views.teacher_login, name='teacher_login'),
    path('teacher/logout/', views.teacher_logout, name='teacher_logout'),
    path('teacher/dashboard/', views.teacher_dashboard, name='teacher_dashboard'),
    path('teacher/create-exam/', views.create_exam, name='create_exam'),
    path('teacher/exam/<int:exam_id>/delete/', views.delete_exam, name='delete_exam'),
    path('teacher/exam/<int:exam_id>/settings/', views.edit_exam_settings, name='edit_exam_settings'),
    path('teacher/exam/<int:exam_id>/add-questions/', views.add_questions, name='add_questions'),
    path('teacher/exam/<int:exam_id>/save-mcq/', views.save_mcq, name='save_mcq'),
    path('teacher/exam/<int:exam_id>/bulk-upload/', views.bulk_upload, name='bulk_upload'),
    path('teacher/exam/<int:exam_id>/generate-ai/', views.generate_ai_questions, name='generate_ai_questions'),
    path('teacher/question/<int:question_id>/delete/', views.delete_question, name='delete_question'),
    path('teacher/exam/<int:exam_id>/students/', views.manage_students, name='manage_students'),
    path('teacher/exam/<int:exam_id>/codes-pdf/', views.download_student_codes_pdf, name='download_student_codes_pdf'),
    path('teacher/access-code/<int:code_id>/delete/', views.delete_access_code, name='delete_access_code'),
    path('teacher/exam/<int:exam_id>/results/', views.exam_results, name='exam_results'),
    path('teacher/exam/<int:exam_id>/analytics/', views.exam_analytics, name='exam_analytics'),
    path('teacher/exam/<int:exam_id>/pdf-all/', views.generate_all_results_pdf, name='generate_all_results_pdf'),
    path('teacher/exam/<int:exam_id>/download-seb/', views.download_seb_config, name='download_seb'),
    path('teacher/exam/<int:exam_id>/seb-setup/', views.seb_setup, name='seb_setup'),
    path('teacher/attempt/<int:attempt_id>/', views.attempt_detail, name='attempt_detail'),
    path('teacher/attempt/<int:attempt_id>/analytics/', views.student_analytics, name='student_analytics'),
    path('teacher/attempt/<int:attempt_id>/pdf/', views.generate_result_pdf, name='generate_result_pdf'),
    path('teacher/sample-students/', views.download_sample_students, name='download_sample_students'),
    path('teacher/profile/', views.teacher_profile, name='teacher_profile'),
    path('exam/<int:exam_id>/register/', views.student_register, name='student_register'),
    path('attempt/<int:attempt_id>/instructions/', views.exam_instructions, name='exam_instructions'),
    path('attempt/<int:attempt_id>/test1/', views.take_test1, name='take_test1'),
    path('attempt/<int:attempt_id>/test1/submit/', views.submit_test1, name='submit_test1'),
    path('attempt/<int:attempt_id>/test1/summary/', views.test1_summary, name='test1_summary'),
    path('attempt/<int:attempt_id>/test2/', views.take_test2, name='take_test2'),
    path('attempt/<int:attempt_id>/test2/submit/', views.submit_test2, name='submit_test2'),
    path('attempt/<int:attempt_id>/submitted/', views.exam_submitted, name='exam_submitted'),
    path('attempt/<int:attempt_id>/result/', views.result, name='result'),
    # path('attempt/<int:attempt_id>/violation/', views.log_violation, name='log_violation'),  # Uncomment after adding log_violation in views.py
    path('teacher/mcq/<int:mcq_id>/ai-single/', views.generate_ai_single, name='generate_ai_single'),
]
